<a href="https://colab.research.google.com/github/Chingiz43/FE-F22-ToDo/blob/main/%D0%A8%D0%B0%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%20%D0%A7%D0%B8%D0%BD%D0%B3%D0%B8%D0%B7%20%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%BE%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import (
    StandardScaler,
    MinMaxScaler,
    OneHotEncoder
)
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Загружаем датасет Titanic
df = sns.load_dataset("titanic")

print("Размер датасета:", df.shape)
print("\nПервые 5 строк:")
display(df.head())

print("\nПропущенные значения:")
display(df.isnull().sum())

Размер датасета: (891, 15)

Первые 5 строк:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

Пропущенные значения:

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [3]:

# Подсчитываем пропущенные значения
missing = df.isnull().sum()

# Рассчитываем процент пропусков
missing_percent = (missing / len(df) * 100).round(2)

# Создаём таблицу результатов
missing_table = pd.DataFrame({
    'Количество пропусков': missing,
    'Процент пропусков (%)': missing_percent
})

print("Анализ пропущенных значений:")
display(missing_table[missing_table['Количество пропусков'] > 0])

Анализ пропущенных значений:

             Количество пропусков  Процент пропусков (%)
age                           177                  19.87
embarked                        2                   0.22
deck                          688                  77.22
embark_town                     2                   0.22

In [5]:

# Создаём копию исходного датасета
df_clean = df.copy()

# Определяем числовые столбцы
numeric_cols = df_clean.select_dtypes(
    include=np.number
).columns.tolist()

# Определяем категориальные столбцы
categorical_cols = df_clean.select_dtypes(
    include=['object', 'category', 'bool']
).columns.tolist()

# Заполняем числовые пропуски медианой
num_imputer = SimpleImputer(strategy='median')
df_clean[numeric_cols] = num_imputer.fit_transform(
    df_clean[numeric_cols]
)

# Заполняем категориальные пропуски модой
cat_imputer = SimpleImputer(strategy='most_frequent')
df_clean[categorical_cols] = cat_imputer.fit_transform(
    df_clean[categorical_cols]
)

print("Количество пропусков после обработки:",
      df_clean.isnull().sum().sum())

display(df_clean.head())

Количество пропусков после обработки: 0

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0.0,3.0,male,22.0,1.0,0.0,7.2500,S,Third,man,True,C,Southampton,no,False
1,1.0,1.0,female,38.0,1.0,0.0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1.0,3.0,female,26.0,0.0,0.0,7.9250,S,Third,woman,False,C,Southampton,yes,True
3,1.0,1.0,female,35.0,1.0,0.0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0.0,3.0,male,35.0,0.0,0.0,8.0500,S,Third,man,True,C,Southampton,no,True

In [6]:

# Создаём копию исходного датасета
df_clean = df.copy()

# Определяем числовые столбцы
numeric_cols = df_clean.select_dtypes(
    include=np.number
).columns.tolist()

# Определяем категориальные столбцы
categorical_cols = df_clean.select_dtypes(
    include=['object', 'category', 'bool']
).columns.tolist()

# Заполняем числовые пропуски медианой
num_imputer = SimpleImputer(strategy='median')
df_clean[numeric_cols] = num_imputer.fit_transform(
    df_clean[numeric_cols]
)

# Заполняем категориальные пропуски наиболее частым значением
cat_imputer = SimpleImputer(strategy='most_frequent')
df_clean[categorical_cols] = cat_imputer.fit_transform(
    df_clean[categorical_cols]
)

print("Пропусков после обработки:",
      df_clean.isnull().sum().sum())

display(df_clean.head())

Пропусков после обработки: 0

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0.0,3.0,male,22.0,1.0,0.0,7.2500,S,Third,man,True,C,Southampton,no,False
1,1.0,1.0,female,38.0,1.0,0.0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1.0,3.0,female,26.0,0.0,0.0,7.9250,S,Third,woman,False,C,Southampton,yes,True
3,1.0,1.0,female,35.0,1.0,0.0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0.0,3.0,male,35.0,0.0,0.0,8.0500,S,Third,man,True,C,Southampton,no,True

In [7]:

# Выбираем признак стоимости билета
fare = df_clean[['fare']]

# Стандартизация
standard_scaler = StandardScaler()
fare_standard = standard_scaler.fit_transform(fare).flatten()

# Нормализация в диапазон от 0 до 1
minmax_scaler = MinMaxScaler()
fare_minmax = minmax_scaler.fit_transform(fare).flatten()

# Сравниваем результаты
comparison = pd.DataFrame({
    'Исходная стоимость': fare['fare'].values,
    'StandardScaler': fare_standard,
    'MinMaxScaler': fare_minmax
})

display(comparison.head(10))

print("Минимум MinMaxScaler:", round(fare_minmax.min(), 4))
print("Максимум MinMaxScaler:", round(fare_minmax.max(), 4))
print("Среднее StandardScaler:", round(fare_standard.mean(), 6))

   Исходная стоимость  StandardScaler  MinMaxScaler
0              7.2500       -0.502445      0.014151
1             71.2833        0.786845      0.139136
2              7.9250       -0.488854      0.015469
3             53.1000        0.420730      0.103644
4              8.0500       -0.486337      0.015713
5              8.4583       -0.478116      0.016510
6             51.8625        0.395814      0.101229
7             21.0750       -0.224083      0.041136
8             11.1333       -0.424256      0.021731
9             30.0708       -0.042956      0.058694

Минимум MinMaxScaler: 0.0
Максимум MinMaxScaler: 1.0
Среднее StandardScaler: 0.0

In [8]:

# Копируем обработанный датасет
df_features = df_clean.copy()

# 1. Размер семьи вместе с пассажиром
df_features['family_size'] = (
    df_features['sibsp'] + df_features['parch'] + 1
)

# 2. Путешествовал ли пассажир один
df_features['is_alone'] = (
    df_features['family_size'] == 1
).astype(int)

# 3. Стоимость билета на одного члена семьи
df_features['fare_per_person'] = (
    df_features['fare'] / df_features['family_size']
)

print("Новые признаки:")
display(df_features[
    ['sibsp', 'parch', 'family_size',
     'is_alone', 'fare', 'fare_per_person']
].head(10))

Новые признаки:

   sibsp  parch  family_size  is_alone     fare  fare_per_person
0    1.0    0.0          2.0         0   7.2500          3.62500
1    1.0    0.0          2.0         0  71.2833         35.64165
2    0.0    0.0          1.0         1   7.9250          7.92500
3    1.0    0.0          2.0         0  53.1000         26.55000
4    0.0    0.0          1.0         1   8.0500          8.05000
5    0.0    0.0          1.0         1   8.4583          8.45830
6    0.0    0.0          1.0         1  51.8625         51.86250
7    3.0    1.0          5.0         0  21.0750          4.21500
8    0.0    2.0          3.0         0  11.1333          3.71110
9    1.0    0.0          2.0         0  30.0708         15.03540

In [9]:

# X — признаки для обучения модели
# y — целевая переменная: выжил пассажир или нет

drop_cols = [
    'survived', 'alive', 'who', 'class',
    'embark_town', 'deck', 'adult_male'
]

X = df_features.drop(columns=drop_cols, errors='ignore')
y = df_features['survived'].astype(int)

# Делим данные на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Размер X:", X.shape)
print("Размер y:", y.shape)
print("Обучающая выборка:", X_train.shape)
print("Тестовая выборка:", X_test.shape)

print("\nРаспределение целевой переменной:")
display(y.value_counts())

Размер X: (891, 11)
Размер y: (891,)
Обучающая выборка: (712, 11)
Тестовая выборка: (179, 11)

Распределение целевой переменной:

survived
0    549
1    342
Name: count, dtype: int64

In [10]:

# Определяем числовые и категориальные признаки
numeric_features = X_train.select_dtypes(
    include=np.number
).columns.tolist()

categorical_features = X_train.select_dtypes(
    include=['object', 'category', 'bool']
).columns.tolist()

# Обработка числовых признаков
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# Обработка категориальных признаков
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

# Объединяем преобразования
preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_transformer, numeric_features),
    ('cat', categorical_transformer, categorical_features)
])

# Обучаем преобразования на тренировочных данных
X_train_prepared = preprocessor.fit_transform(X_train)

# Применяем их к тестовым данным
X_test_prepared = preprocessor.transform(X_test)

print("Подготовленная обучающая матрица:",
      X_train_prepared.shape)
print("Подготовленная тестовая матрица:",
      X_test_prepared.shape)

Подготовленная обучающая матрица: (712, 15)
Подготовленная тестовая матрица: (179, 15)

## Вывод

В ходе лабораторной работы № 2 были изучены методы предобработки данных и Feature Engineering с использованием библиотек Pandas, NumPy и Scikit-Learn. На примере датасета Titanic был проведён анализ пропущенных значений, выполнено заполнение числовых пропусков медианой и категориальных пропусков наиболее частыми значениями.

Было проведено сравнение методов StandardScaler и MinMaxScaler. Созданы три новых признака: family_size, is_alone и fare_per_person. Сформированы матрица признаков X и целевая переменная y, а данные разделены на обучающую и тестовую выборки.

Для комплексной предобработки использованы SimpleImputer, StandardScaler, OneHotEncoder, ColumnTransformer и Pipeline. Параметры преобразований вычислялись только на обучающей выборке, что позволило избежать утечки данных.

Таким образом, цель лабораторной работы достигнута: данные подготовлены к последующему обучению моделей машинного обучения.